version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_PASSWORD:  postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      database_hostname: db
      database_port: 5432
      database_username: postgres
      database_password: postgres
      database_name: fastapi
      secret_key: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      algorithm : HS256
      access_token_expire_minutes : 60
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --port 4000 --host 0.0.0.0 --reload
volumes:
  postgres_data: